# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.bw_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.bw_btn.setGeometry(QtCore.QRect(510, 470, 75, 23))
        self.bw_btn.setObjectName("bw_btn")
        self.sharp_bttn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.sharp_bttn.setGeometry(QtCore.QRect(410, 480, 81, 31))
        self.sharp_bttn.setObjectName("sharp_bttn")
        self.left_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.left_btn.setGeometry(QtCore.QRect(50, 470, 111, 31))
        self.left_btn.setObjectName("left_btn")
        self.right_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.right_btn.setGeometry(QtCore.QRect(210, 480, 75, 23))
        self.right_btn.setObjectName("right_btn")
        self.mirror = QtWidgets.QPushButton(parent=self.centralwidget)
        self.mirror.setGeometry(QtCore.QRect(320, 470, 75, 23))
        self.mirror.setObjectName("mirror")
        self.files_list = QtWidgets.QListWidget(parent=self.centralwidget)
        self.files_list.setGeometry(QtCore.QRect(-70, -110, 641, 341))
        self.files_list.setObjectName("files_list")
        self.photo_lb = QtWidgets.QLabel(parent=self.centralwidget)
        self.photo_lb.setGeometry(QtCore.QRect(240, 240, 101, 41))
        self.photo_lb.setObjectName("photo_lb")
        self.dir_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.dir_btn.setGeometry(QtCore.QRect(610, 10, 141, 61))
        self.dir_btn.setObjectName("dir_btn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bw_btn.setText(_translate("MainWindow", "Ч/Б"))
        self.sharp_bttn.setText(_translate("MainWindow", "різкість"))
        self.left_btn.setText(_translate("MainWindow", "вліво"))
        self.right_btn.setText(_translate("MainWindow", "вправо"))
        self.mirror.setText(_translate("MainWindow", "дзеркало"))
        self.photo_lb.setText(_translate("MainWindow", "картинка"))
        self.dir_btn.setText(_translate("MainWindow", "папка"))
